name: jmagick Makefile CI (multiple jdk versions)

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest # jammy

    name:  ${{ matrix.jdk }} on ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        jdk: ['8', '17']
        os: ['ubuntu', 'bookworm']
        exclude:
          - jdk: '8'
            os: 'bookworm'

    container:
      image: dpokidov/imagemagick:7.1.1-31-2-${{ matrix.os }}
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Package update
        run: apt-get update -y && apt-get install -y sudo curl wget apt-utils

      - name: Install build tools
        run: apt-get install -y build-essential pkg-config openjdk-${{ matrix.jdk }}-jdk

      - name: Gradle build
        run: ./gradlew build

      - name: Gradle test
        run: ./gradlew test
